# Generated by Django 4.2.7 on 2024-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_leaverequestdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ลากิจ', 'Personal Leave'), ('ลาป่วย', 'Sick Leave'), ('อื่น ๆ', 'Other Leave')], default='undefined', max_length=20),
        ),
    ]
