# Generated by Django 5.0 on 2024-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_myfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
            ],
        ),
    ]
