# Generated by Django 5.0 on 2024-03-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leaverequest_leave_type'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequestdetail',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
