# Generated by Django 5.0 on 2024-01-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
