# Generated by Django 5.0 on 2024-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaverequestdetail_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
        migrations.AddField(
            model_name='leaverequestdetail',
            name='status',
            field=models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
