# Generated by Django 5.0 on 2024-03-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_leaverequest_status_leaverequestdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='file_id',
        ),
        migrations.AddField(
            model_name='files',
            name='leave_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leaverequest'),
        ),
    ]
