# Generated by Django 5.0 on 2024-01-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
    ]
