# Generated by Django 5.0 on 2024-01-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
