# Generated by Django 5.0 on 2024-02-16 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 0, 50, 16, 756723, tzinfo=datetime.timezone.utc)),
        ),
    ]
