# Generated by Django 5.0 on 2024-01-29 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 4, 23, 15, 537828, tzinfo=datetime.timezone.utc)),
        ),
    ]
