# Generated by Django 5.0 on 2024-03-11 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 2, 9, 51, 325971, tzinfo=datetime.timezone.utc)),
        ),
    ]
