# Generated by Django 5.0 on 2024-03-12 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 3, 19, 9, 249853, tzinfo=datetime.timezone.utc)),
        ),
    ]
