# Generated by Django 5.0 on 2024-03-23 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 21, 55, 13, 947222, tzinfo=datetime.timezone.utc)),
        ),
    ]
